version: '3.8'

services:
  app:
    image:
      build:
        context: .
        dockerfile: Dockerfile

  db:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
